---
title: "Untitled"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
---

```{r carga-paquetes, message=FALSE, warning=FALSE}
# Carga de paquetes
library(dplyr)
library(sf)
library(DT)
library(plotly)
library(leaflet)
library(flexdashboard)
```

```{r carga-datos}
# Registros de presencia de Junco vulcani
orchidaceae <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/gbif/orchidaceae-cr-registros.csv",
    options = c(
      "X_POSSIBLE_NAMES=decimalLongitude",
      "Y_POSSIBLE_NAMES=decimalLatitude"
    ),
    quiet = TRUE
  )
# Asignación de CRS
st_crs(orchidaceae) = 4326
# Capa  de cantones
cantones <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_cantones_simp_wgs84.geojson",
    quiet = TRUE
  )

provincias <-
  st_read(
    "https://raw.githubusercontent.com/gf0604-procesamientodatosgeograficos/2021i-datos/main/ign/delimitacion-territorial-administrativa/cr_provincias_simp_wgs84.geojson",
    quiet = TRUE
  )

```

```{r cruce de datos}
# Cruce espacial de cantones y provincias
orchidaceae <- 
  orchidaceae %>%
  st_join(cantones["canton"]) %>%
  st_join(provincias["provincia"])
```

Registros de presencia, estacionalidad e historial
=======================================================================

Row {data-height=100}
-----------------------------------------------------------------------

### Registros de presencia {.value-box}
```{r valuebox}
valueBox(value = nrow(orchidaceae), 
         caption = "Registros de presencia", 
         icon = "fas fa-feather-alt",
         color = "orange"
)
```

### Cantidad de géneros {.value-box}
```{r valuebox2}
vbox2 <- orchidaceae %>%
  filter(!is.na(genus) & genus != "") %>%
  group_by(genus) %>% 
  summarise(registros = n())
valueBox(value = nrow(vbox2), 
         icon = "fas fa-fan", 
         color = "cyan")
```


### Cantidad de especies {.value-box}
```{r especies}
vbox3 <- orchidaceae %>%
  filter(!is.na(species) & species != "") %>%
  group_by(species) %>% 
  summarise(registros = n())
valueBox(value = nrow(vbox3), 
         icon = "fas fa-fan", 
         color = "yellow")
```


Row {data-height=550}
-----------------------------------------------------------------------

```{r limpieza}
# Conversión valores NA a 0

orchidaceae$coordinateUncertaintyInMeters[orchidaceae$coordinateUncertaintyInMeters == ""] <- "0"

orchidaceae <- 
  orchidaceae %>%
  mutate(coordinateUncertaintyInMeters = as.numeric(coordinateUncertaintyInMeters)) %>%
  mutate(eventDate = as.Date(eventDate, "%Y-%m-%d"))
# Limpieza  valores de alta incertidumbre (menor a 1000)
orchidaceae <-
  orchidaceae %>%
  filter(!is.na(coordinateUncertaintyInMeters) & coordinateUncertaintyInMeters <= 1000)

```


### Tabla de registros de Orchidaceae

```{r data-table, message=FALSE, warning=FALSE}
orchidaceae %>%
  st_drop_geometry() %>%
  select(species, eventDate, stateProvince, canton) %>%
  datatable(colnames = c(
    "Especie",
    "Fecha",
    "Provincia",
    "Cantón"), 
    options = list(searchHighlight = TRUE,
                   language = list(url = '//cdn.datatables.net/plug-ins/1.10.25/i18n/Spanish.json'),
                   pageLength = 14)
  )
```

Row {data-height=350}
-----------------------------------------------------------------------

### Chart B

```{r}

```

### Chart C

```{r}

```

